// Code generated by "stringer -type=OpCode -trimprefix=OpCode"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeGetGlobal-0]
	_ = x[OpCodeSetGlobal-1]
	_ = x[OpCodeSetGlobalConst-2]
	_ = x[OpCodeSetGlobalGlobal-3]
	_ = x[OpCodeLoadConst-4]
	_ = x[OpCodeCall-5]
	_ = x[OpCodeLoadNil-6]
	_ = x[OpCodeLoadBool-7]
	_ = x[OpCodeLoadInt-8]
	_ = x[OpCodeMove-9]
	_ = x[OpCodeNewTable-10]
	_ = x[OpCodeSetTable-11]
	_ = x[OpCodeSetTableConst-12]
	_ = x[OpCodeSetField-13]
	_ = x[OpCodeSetFieldConst-14]
	_ = x[OpCodeSetInt-15]
	_ = x[OpCodeSetIntConst-16]
	_ = x[OpCodeSetList-17]
	_ = x[OpCodeGetTable-18]
	_ = x[OpCodeGetField-19]
	_ = x[OpCodeGetInt-20]
	_ = x[OpCodeNegate-21]
	_ = x[OpCodeNot-22]
	_ = x[OpCodeBitNot-23]
	_ = x[OpCodeLength-24]
}

const _OpCode_name = "GetGlobalSetGlobalSetGlobalConstSetGlobalGlobalLoadConstCallLoadNilLoadBoolLoadIntMoveNewTableSetTableSetTableConstSetFieldSetFieldConstSetIntSetIntConstSetListGetTableGetFieldGetIntNegateNotBitNotLength"

var _OpCode_index = [...]uint8{0, 9, 18, 32, 47, 56, 60, 67, 75, 82, 86, 94, 102, 115, 123, 136, 142, 153, 160, 168, 176, 182, 188, 191, 197, 203}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
