// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[getGlobal-0]
	_ = x[setGlobal-1]
	_ = x[setGlobalConst-2]
	_ = x[setGlobalGlobal-3]
	_ = x[loadConst-4]
	_ = x[call-5]
	_ = x[loadNil-6]
	_ = x[loadBool-7]
	_ = x[loadInt-8]
	_ = x[move-9]
	_ = x[newTable-10]
	_ = x[setTable-11]
	_ = x[setField-12]
	_ = x[setList-13]
}

const _OpCode_name = "getGlobalsetGlobalsetGlobalConstsetGlobalGloballoadConstcallloadNilloadBoolloadIntmovenewTablesetTablesetFieldsetList"

var _OpCode_index = [...]uint8{0, 9, 18, 32, 47, 56, 60, 67, 75, 82, 86, 94, 102, 110, 117}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
