// Code generated by "stringer -type=Type -trimprefix Type"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeString-0]
	_ = x[TypeFloat-1]
	_ = x[TypeInteger-2]
	_ = x[TypeFunction-3]
	_ = x[TypeBoolean-4]
	_ = x[TypeNil-5]
	_ = x[TypeTable-6]
}

const _Type_name = "StringFloatIntegerFunctionBooleanNilTable"

var _Type_index = [...]uint8{0, 6, 11, 18, 26, 33, 36, 41}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
