// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[And-1]
	_ = x[Break-2]
	_ = x[Do-3]
	_ = x[Else-4]
	_ = x[ElseIf-5]
	_ = x[End-6]
	_ = x[False-7]
	_ = x[For-8]
	_ = x[Function-9]
	_ = x[Global-10]
	_ = x[Goto-11]
	_ = x[If-12]
	_ = x[In-13]
	_ = x[Local-14]
	_ = x[Nil-15]
	_ = x[Not-16]
	_ = x[Or-17]
	_ = x[Repeat-18]
	_ = x[Return-19]
	_ = x[Then-20]
	_ = x[True-21]
	_ = x[Until-22]
	_ = x[While-23]
	_ = x[Plus-24]
	_ = x[Minus-25]
	_ = x[Asterisk-26]
	_ = x[Slash-27]
	_ = x[Percentage-28]
	_ = x[Cirumflex-29]
	_ = x[Hashtag-30]
	_ = x[Ampersand-31]
	_ = x[Tilde-32]
	_ = x[Pipe-33]
	_ = x[RightShfit-34]
	_ = x[LeftShift-35]
	_ = x[EscpaedSlash-36]
	_ = x[Equal-37]
	_ = x[NotEqual-38]
	_ = x[SmallerThan-39]
	_ = x[GreaterThan-40]
	_ = x[Smaller-41]
	_ = x[Greater-42]
	_ = x[Assign-43]
	_ = x[OpenBracket-44]
	_ = x[ClosedBracket-45]
	_ = x[OpenBrace-46]
	_ = x[ClosedBrace-47]
	_ = x[OpenSquareBracket-48]
	_ = x[ClosedSquareBracket-49]
	_ = x[DoubleColon-50]
	_ = x[SemiColon-51]
	_ = x[Colon-52]
	_ = x[Comma-53]
	_ = x[Dot-54]
	_ = x[DoubleDot-55]
	_ = x[TrippleDot-56]
	_ = x[Float-57]
	_ = x[Integer-58]
	_ = x[String-59]
	_ = x[Identifier-60]
}

const _TokenType_name = "AndBreakDoElseElseIfEndFalseForFunctionGlobalGotoIfInLocalNilNotOrRepeatReturnThenTrueUntilWhilePlusMinusAsteriskSlashPercentageCirumflexHashtagAmpersandTildePipeRightShfitLeftShiftEscpaedSlashEqualNotEqualSmallerThanGreaterThanSmallerGreaterAssignOpenBracketClosedBracketOpenBraceClosedBraceOpenSquareBracketClosedSquareBracketDoubleColonSemiColonColonCommaDotDoubleDotTrippleDotFloatIntegerStringIdentifier"

var _TokenType_index = [...]uint16{0, 3, 8, 10, 14, 20, 23, 28, 31, 39, 45, 49, 51, 53, 58, 61, 64, 66, 72, 78, 82, 86, 91, 96, 100, 105, 113, 118, 128, 137, 144, 153, 158, 162, 172, 181, 193, 198, 206, 217, 228, 235, 242, 248, 259, 272, 281, 292, 309, 328, 339, 348, 353, 358, 361, 370, 380, 385, 392, 398, 408}

func (i TokenType) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
