// Code generated by "stringer -type=expressionType -trimprefix=expression"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[expressionNil-0]
	_ = x[expressioinBoolean-1]
	_ = x[expressionInteger-2]
	_ = x[expressionFloat-3]
	_ = x[expressionString-4]
	_ = x[expressionLocal-5]
	_ = x[expressionGlobal-6]
	_ = x[expressionIndex-7]
	_ = x[expressionIndexField-8]
	_ = x[expressionIndexInt-9]
	_ = x[expressionCall-10]
	_ = x[expressionUnaryOperation-11]
}

const _expressionType_name = "NilexpressioinBooleanIntegerFloatStringLocalGlobalIndexIndexFieldIndexIntCallUnaryOperation"

var _expressionType_index = [...]uint8{0, 3, 21, 28, 33, 39, 44, 50, 55, 65, 73, 77, 91}

func (i expressionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_expressionType_index)-1 {
		return "expressionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _expressionType_name[_expressionType_index[idx]:_expressionType_index[idx+1]]
}
